# Generated by Django 5.2.1 on 2025-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfile',
            options={'verbose_name': 'Fichier de test', 'verbose_name_plural': 'Fichiers de test'},
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom original'),
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (bytes)'),
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom original'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
